<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <Company>yikz</Company>
    <Product>Yikz Clipboard</Product>
    <Copyright>Copyright (c) yikz</Copyright>
    <Deterministic>true</Deterministic>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
</Project>
