import AppKit
import ImageIO
import UniformTypeIdentifiers
import ClipCore

enum RawClipboard: Sendable {
    case text(String)
    case image(Data)
    case files([URL])
}

struct CapturedClipboard: Sendable {
    var raw: RawClipboard
    var sourceApp: String?
}

@MainActor
final class PasteboardMonitor {
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let origin = NSPasteboard.PasteboardType(Proto.originPasteboardType)

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var ignored = Set<Int>()
    private var timer: DispatchSourceTimer?
    var onCapture: ((CapturedClipboard) -> Void)?

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let t = DispatchSource.makeTimerSource(queue: .main)
        t.schedule(deadline: .now() + .milliseconds(300), repeating: .milliseconds(300), leeway: .milliseconds(100))
        t.setEventHandler { [weak self] in
            MainActor.assumeIsolated {
                self?.tick()
            }
        }
        t.resume()
        timer = t
        Log.info("Clipboard monitor started", "clipboard")
    }

    func stop() {
        timer?.cancel()
        timer = nil
    }

    func markOwnWrite(changeCount: Int) {
        ignored.insert(changeCount)
        lastChangeCount = changeCount
        if ignored.count > 16 {
            ignored = Set(ignored.sorted().suffix(8))
        }
    }

    private func tick() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        if ignored.remove(count) != nil { return }
        guard let captured = capture(force: false) else { return }
        onCapture?(captured)
    }

    func capture(force: Bool) -> CapturedClipboard? {
        let types = Set(pasteboard.types ?? [])
        if types.contains(Self.concealed) || types.contains(Self.transient) || types.contains(Self.autoGenerated) {
            Log.info("Skipped clipboard change marked concealed or transient", "clipboard")
            return nil
        }
        if types.contains(Self.origin) && !force {
            return nil
        }
        let source = PasteboardMonitor.sourceAppName()
        if types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return CapturedClipboard(raw: .files(urls), sourceApp: source)
        }
        let hasRichText = types.contains(.rtf) || types.contains(.rtfd) || types.contains(.html)
        let text = pasteboard.string(forType: .string)
        if hasRichText, let text, !text.isEmpty {
            return CapturedClipboard(raw: .text(text), sourceApp: source)
        }
        if let png = pasteboard.data(forType: .png) {
            return CapturedClipboard(raw: .image(png), sourceApp: source)
        }
        if let tiff = pasteboard.data(forType: .tiff) {
            return CapturedClipboard(raw: .image(tiff), sourceApp: source)
        }
        let imageTypes: [NSPasteboard.PasteboardType] = [
            NSPasteboard.PasteboardType(UTType.jpeg.identifier),
            NSPasteboard.PasteboardType(UTType.heic.identifier),
            NSPasteboard.PasteboardType(UTType.webP.identifier),
            NSPasteboard.PasteboardType(UTType.gif.identifier)
        ]
        for t in imageTypes where types.contains(t) {
            if let d = pasteboard.data(forType: t) {
                return CapturedClipboard(raw: .image(d), sourceApp: source)
            }
        }
        if let text, !text.isEmpty {
            return CapturedClipboard(raw: .text(text), sourceApp: source)
        }
        return nil
    }

    static func sourceAppName() -> String? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        if app.bundleIdentifier == Bundle.main.bundleIdentifier { return nil }
        return app.localizedName
    }
}

@MainActor
final class PasteboardWriter {
    weak var monitor: PasteboardMonitor?

    func write(_ content: ApplyContent, itemId: String) -> Bool {
        let pb = NSPasteboard.general
        pb.clearContents()
        var ok = false
        switch content {
        case .text(let s):
            let item = NSPasteboardItem()
            item.setString(s, forType: .string)
            item.setString(itemId, forType: PasteboardMonitor.origin)
            ok = pb.writeObjects([item])
        case .image(let png):
            let item = NSPasteboardItem()
            item.setData(png, forType: .png)
            if let tiff = NSBitmapImageRep(data: png)?.tiffRepresentation {
                item.setData(tiff, forType: .tiff)
            }
            item.setString(itemId, forType: PasteboardMonitor.origin)
            ok = pb.writeObjects([item])
        case .files(let urls):
            let items = urls.enumerated().map { i, url -> NSPasteboardItem in
                let item = NSPasteboardItem()
                item.setString(url.absoluteString, forType: .fileURL)
                if i == 0 {
                    item.setString(itemId, forType: PasteboardMonitor.origin)
                    item.setString(url.lastPathComponent, forType: .string)
                }
                return item
            }
            ok = pb.writeObjects(items)
        }
        monitor?.markOwnWrite(changeCount: pb.changeCount)
        if !ok { Log.error("Writing to the clipboard failed", "clipboard") }
        return ok
    }
}

enum ContentBuilder {
    static let maxFilesBytes: Int64 = 2 * 1024 * 1024 * 1024

    static func build(_ captured: CapturedClipboard, outgoingDir: URL, inlineMax: Int64 = Proto.inlineMaxBytes) throws -> OutgoingContent? {
        switch captured.raw {
        case .text(let s):
            return OutgoingContent.text(s, sourceApp: captured.sourceApp)
        case .image(let data):
            return try image(data, sourceApp: captured.sourceApp)
        case .files(let urls):
            return try files(urls, sourceApp: captured.sourceApp, outgoingDir: outgoingDir, inlineMax: inlineMax)
        }
    }

    static func image(_ data: Data, sourceApp: String?) throws -> OutgoingContent? {
        guard let src = CGImageSourceCreateWithData(data as CFData, nil), CGImageSourceGetCount(src) > 0,
              let cg = CGImageSourceCreateImageAtIndex(src, 0, nil) else {
            Log.warning("Clipboard image could not be decoded", "clipboard")
            return nil
        }
        let isPNG = data.starts(with: [0x89, 0x50, 0x4E, 0x47])
        let png: Data
        if isPNG {
            png = data
        } else {
            let out = NSMutableData()
            guard let dest = CGImageDestinationCreateWithData(out, UTType.png.identifier as CFString, 1, nil) else { return nil }
            CGImageDestinationAddImage(dest, cg, nil)
            guard CGImageDestinationFinalize(dest) else { return nil }
            png = out as Data
        }
        let dims = ImageDimensions(width: cg.width, height: cg.height)
        return OutgoingContent.image(png: png, dimensions: dims, thumbnail: thumbnail(from: src), sourceApp: sourceApp)
    }

    static func thumbnail(from src: CGImageSource) -> Data? {
        var side = Proto.thumbnailMaxSide
        var quality = 0.8
        for _ in 0..<6 {
            let opts: [CFString: Any] = [
                kCGImageSourceCreateThumbnailFromImageAlways: true,
                kCGImageSourceThumbnailMaxPixelSize: side,
                kCGImageSourceCreateThumbnailWithTransform: true,
                kCGImageSourceShouldCacheImmediately: true
            ]
            guard let thumb = CGImageSourceCreateThumbnailAtIndex(src, 0, opts as CFDictionary) else { return nil }
            let out = NSMutableData()
            guard let dest = CGImageDestinationCreateWithData(out, UTType.jpeg.identifier as CFString, 1, nil) else { return nil }
            CGImageDestinationAddImage(dest, flattened(thumb) ?? thumb, [kCGImageDestinationLossyCompressionQuality: quality] as CFDictionary)
            guard CGImageDestinationFinalize(dest) else { return nil }
            if out.length + Proto.sealOverhead <= Proto.thumbMaxBytes {
                return out as Data
            }
            quality -= 0.15
            side = max(64, side * 3 / 4)
        }
        return nil
    }

    static func flattened(_ image: CGImage) -> CGImage? {
        guard let ctx = CGContext(
            data: nil, width: image.width, height: image.height, bitsPerComponent: 8, bytesPerRow: 0,
            space: CGColorSpace(name: CGColorSpace.sRGB)!, bitmapInfo: CGImageAlphaInfo.noneSkipLast.rawValue
        ) else { return nil }
        ctx.setFillColor(CGColor(gray: 1, alpha: 1))
        ctx.fill(CGRect(x: 0, y: 0, width: image.width, height: image.height))
        ctx.draw(image, in: CGRect(x: 0, y: 0, width: image.width, height: image.height))
        return ctx.makeImage()
    }

    static func files(_ urls: [URL], sourceApp: String?, outgoingDir: URL, inlineMax: Int64) throws -> OutgoingContent? {
        var regular: [URL] = []
        var skippedDirs = 0
        for url in urls {
            let resolved = url.resolvingSymlinksInPath()
            var isDir: ObjCBool = false
            guard FileManager.default.fileExists(atPath: resolved.path, isDirectory: &isDir) else { continue }
            if isDir.boolValue {
                skippedDirs += 1
                continue
            }
            regular.append(resolved)
        }
        if skippedDirs > 0 {
            Log.info("Skipped \(skippedDirs) folder(s); only regular files are synced", "clipboard")
        }
        guard !regular.isEmpty else { return nil }
        if regular.count > Proto.maxFilesPerItem {
            Log.warning("Too many files (\(regular.count)); only the first \(Proto.maxFilesPerItem) are sent", "clipboard")
            regular = Array(regular.prefix(Proto.maxFilesPerItem))
        }
        let total = regular.reduce(Int64(0)) { sum, u in
            sum + Int64((try? u.resourceValues(forKeys: [.fileSizeKey]))?.fileSize ?? 0)
        }
        if total > maxFilesBytes {
            Log.warning("Files total \(total) bytes, above the 2 GB send limit; not sent", "clipboard")
            return nil
        }
        let names = YCF1.uniqueNames(regular.map { $0.lastPathComponent })
        let sources = zip(names, regular).map { YCF1.SourceFile(name: $0.0, url: $0.1) }
        try? FileManager.default.createDirectory(at: outgoingDir, withIntermediateDirectories: true)
        let archive = outgoingDir.appendingPathComponent("\(UUID().uuidString).ycf1")
        let infos = try YCF1.write(files: sources, to: archive)
        let size = Int64((try? archive.resourceValues(forKeys: [.fileSizeKey]))?.fileSize ?? 0)
        if size <= inlineMax {
            let data = try Data(contentsOf: archive)
            try? FileManager.default.removeItem(at: archive)
            return OutgoingContent.files(archive: .data(data), files: infos, sourceApp: sourceApp)
        }
        return OutgoingContent.files(archive: .file(archive, deleteAfter: true), files: infos, sourceApp: sourceApp)
    }
}
